AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "Creates the Amazon Kinesis Stream resources."

Resources:
  EventStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

Outputs:
  StreamName:
    Value: !Ref EventStream
    Description: The Amazon Kinesis stream name.
  StreamArn:
    Value: !GetAtt EventStream.Arn
    Description: The Amazon Kinesis stream ARN.
